[package]
name = "dzq"
version = "0.1.0"
authors = ["qiu"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.4.0"
itertools = "0.9.0"
mysql = "*"
futures = "0.3.4"