[package]
name = "simple_poolweb"
version = "0.1.0"
authors = ["qiu"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "1.0.17"
quote = "1.0.3"
proc-macro2 = "1.0.10"

# proc-macro = true